config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :recipes, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :cuisines, only: [:show, :new, :create, :edit, :update]
  resources :recipe_types, only: [:show, :new, :create, :edit, :update]

  resources :users, only: [] do
    resources :recipes, only: [:index]
  end

  get "/search", to: "home#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false,
                                 message: 'Cozinha já existe' },
                   presence: { message: 'Você deve informar o nome da cozinha' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :user

  validates :title, :recipe_type, :difficulty, :cook_time, :ingredients,
            :cook_method, presence: true

  has_attached_file :photo
  validates_attachment_content_type :photo, content_type: %r{\Aimage\/.*\z}
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false,
                                 message: 'Tipo de receita já existe' },
                   presence: { message: 'Você deve informar o nome do '\
                                        'tipo de receita' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate_admin!
    redirect_to(root_path, alert: 'Usuário sem permissão') unless admin_user?
  end

  def admin_user?
    current_user&.admin?
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :find_cuisine, only: %i[show edit update]
  before_action :authenticate_admin!, only: %i[new edit]

  def show; end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to cuisine_path(@cuisine.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cuisine.update(cuisine_params)
      flash[:notice] = 'Cozinha alterada com sucesso'
      redirect_to @cuisine
    else
      flash[:alert] = 'Erro ao alterar a cozinha'
      render :edit
    end
  end

  private

  def find_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def search
    param_title = params[:title]

    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all

    @recipes = if param_title.blank?
                 Recipe.all
               else
                 Recipe.where('title LIKE :title', title: "%#{param_title}%")
               end
    render :index
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :find_recipe_type, only: %i[show edit update]
  before_action :authenticate_admin!, only: %i[new edit]

  def show; end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      redirect_to recipe_type_path(@recipe_type.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @recipe_type.update(recipe_type_params)
      redirect_to @recipe_type, notice: 'Tipo de receita alterado com sucesso'
    else
      flash[:alert] = 'Erro ao alterar o tipo de receita'
      render :edit
    end
  end

  private

  def find_recipe_type
    @recipe_type = RecipeType.find(params[:id])
  end

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit create]

  def index
    @user_recipes = User.find(params[:user_id]).recipes
  end

  def show
    @recipe = find_recipe_by_id_param
  end

  def new
    @recipe = Recipe.new
    load_recipes_associations
  end

  def create
    @recipe = Recipe.new recipe_params
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      load_recipes_associations
      flash_error_message
      render :new
    end
  end

  def edit
    @recipe = find_recipe_by_id_param
    load_recipes_associations
  end

  def update
    @recipe = Recipe.find recipe_id_param
    if @recipe.update recipe_params
      redirect_to recipe_path(@recipe.id)
    else
      load_recipes_associations
      flash_error_message
      render :edit
    end
  end

  def destroy
    Recipe.delete(params[:id])
    redirect_to user_recipes_path(current_user),
                notice: 'Receita apagada com sucesso'
  end

  private

  def find_recipe_by_id_param
    Recipe.find recipe_id_param
  end

  def load_recipes_associations
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :cook_method, :photo)
  end

  def recipe_id_param
    params[:id]
  end

  def flash_error_message
    flash[:error] = 'Você deve informar todos os dados da receita'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_present(user)
    UserPresenter.new(user)
  end
end

app/views/cuisines/_form.html.erb
<% @cuisine.errors.full_messages.each do |m| %>
  <p><%= m %></p>
<% end %>

<%= form_for @cuisine do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/cuisines/edit.html.erb
<h1><%= @cuisine.name %></h1>

<%= render 'form' %>

app/views/cuisines/new.html.erb
<h1>Cozinha</h1>

<%= render 'form' %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>

<%= link_to 'Editar', edit_cuisine_path(@cuisine) %>

<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>

<%= render @cuisine.recipes %>

app/views/home/_admin.html.erb
<div>Administrador |
 <%= link_to 'Adicionar cozinha', new_cuisine_path %> |
 <%= link_to 'Adicionar tipo de receita', new_recipe_type_path %> |
 <%= link_to 'Sair', destroy_user_session_path, method: :delete %></div>

app/views/home/_user.html.erb
<div>Olá <%= current_user.email %> | <%= link_to 'Minhas receitas', user_recipes_path(current_user) %> | <%= link_to 'Sair', destroy_user_session_path, method: :delete %></div>

app/views/home/_visitor.html.erb
<%= link_to 'Entrar', new_user_session_path %>

app/views/home/index.html.erb
<%= render user_present(current_user).checkout_partial %>

<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<div>
  <%= form_tag("/search", method: "get") do %>
    <%= label_tag :title, "Buscar por" %>
    <%= text_field_tag :title %>
    <%= submit_tag "Buscar" %>
  <% end %>

<h3>Cozinhas</h3>
<ul>
  <% @cuisines.each do |cuisine| %>
    <li><%= link_to cuisine.name, cuisine %></li>
  <% end %>
</ul>

<h3>Tipos de receitas</h3>
<ul>
<% @recipe_types.each do |recipe_type| %>
  <li><%= link_to recipe_type.name, recipe_type %></li>
<% end %>
</ul>

<% if @recipes.empty? %>
  <p>Nenhuma receita encontrada</p>
<% end %>

<%= render @recipes %>

<%= link_to "Enviar uma receita", new_recipe_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipe_types/_form.html.erb
<% @recipe_type.errors.full_messages.each do |m| %>
  <p><%= m %></p>
<% end %>

<%= form_for @recipe_type do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/recipe_types/edit.html.erb
<h1><%= @recipe_type.name %></h1>

<%= render 'form' %>

app/views/recipe_types/new.html.erb
<h1>Tipo de Receita</h1>

<%= render 'form' %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<%= link_to 'Editar', edit_recipe_type_path(@recipe_type) %>

<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo</p>
<% end %>

<%= render @recipe_type.recipes %>

app/views/recipes/_form.html.erb
<p><%= flash[:error] %></p>

<%= form_for(@recipe, html: { multipart: true }) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type_id %>
    <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
  </div>
  <div>
    <%= f.label :cuisine_id %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>
  </div>
  <div>
    <%= f.label :difficulty %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time %>
    <%= f.number_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients %>
  </div>
  <div>
    <%= f.label :cook_method %>
    <%= f.text_field :cook_method %>
  </div>
  <div>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div>
    <%= f.submit t('recipes.edit.send') %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= link_to recipe.title, recipe_path(recipe) %></h1>
<ul>
  <li><%= recipe.recipe_type.name %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos</li>
</ul>

app/views/recipes/edit.html.erb
<h1><%= t('recipes.edit.title') %></h1>

<%= render "form" %>

<%= link_to t('recipes.edit.cancel'), recipe_path(@recipe.id) %>

app/views/recipes/index.html.erb
<h2><%= t('users.recipes.index.my_recipes') %></h2>

<% if @user_recipes.empty? %>
  <h3><%= t('users.recipes.index.empty_recipes') %></h3>
<% end %>

<% @user_recipes.each do |recipe| %>
  <h3><%= link_to recipe.title, recipe %></h3>
  <%= link_to t('users.recipes.index.edit'), edit_recipe_path(recipe) %>  
  <%= link_to t('users.recipes.index.delete'), recipe, method: :delete %>
<% end %>

app/views/recipes/new.html.erb
<h1><%= t('recipes.new.title') %></h1>

<%= render "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>
<%= image_tag @recipe.photo.url %>

<% if user_present(current_user).can_edit(@recipe) %>
  <%= link_to "Editar", edit_recipe_path(@recipe.id) %>
<% end %>
<%= link_to "Voltar", :root %>